### ISSUE TITLE
Add OpenSSL 3 support

### ISSUE THREAD

**Issue by lucaskanashiro** [nov/json-jwt#100]
Running the tests with ruby 3.0, in Ubuntu 22.04 which already has OpenSSL 3, I got the following failures:

https://paste.debian.net/1234644/

All those failures are happening because of some API changes in the openssl gem version 3.0.0:

https://github.com/ruby/openssl/blob/master/History.md#version-300

**Comment by nov** [comment]
Hi, I could reproduce these errors.
It seems I need lots of times to fix them though..

**Comment by nov** [comment]
ref.) https://github.com/cedarcode/webauthn-ruby/issues/359#issuecomment-1088198748
