### ISSUE TITLE
How to report security vulnerabilities

### ISSUE THREAD

**Issue by btoews** [nov/json-jwt#108]
The documentation for this project doesn't specify how security vulnerabilities should be reported. I sent an email on September 9th to the address listed in the gemspec and haven't received a response. Would opening an issue/PR be better? Thanks.

**Comment by nov** [comment]
email is OK, but I couldn't notice your mail in September and can't find it

**Comment by btoews** [comment]
I sent it again. It’s from a latacora.com email address.
