### ISSUE TITLE
Backport of CVE fix?

### ISSUE THREAD

**Issue by mjankowski** [nov/json-jwt#121]
Thanks for the quick response and version release for this [CVE](https://github.com/nov/json-jwt/issues/119)!

Any chance of getting this backported and getting a 1.15.x release? Updating from 1.15.x to 1.16.x requires a faraday v1 to v2 update -- and for projects which still have dependencies locked to faraday v1.x they won't be able to do this `json-jwt` update.

Understood if this is not viable, but figured I'd ask.

**Comment by Capncavedan** [comment]
Would also really appreciate a backport of the CVE fix!

**Comment by Capncavedan** [comment]
Opened PR https://github.com/nov/json-jwt/pull/122

**Comment by nov** [comment]
`v1.15.3.1` is released

**Comment by Capncavedan** [comment]
thank you, @nov!
