### ISSUE TITLE
A128CBC-HS256

### ISSUE THREAD

**Issue by jondeandres** [nov/json-jwt#14]
Hi,

in the draft in http://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-14 i can read this:
### 

Replaced "A128CBC+HS256" and "A256CBC+HS512" with "A128CBC-HS256" and "A256CBC-HS512".  The new algorithms perform the same cryptographic computations as [I-D.mcgrew-aead-aes-cbc-hmac-sha2], but with the Initialization Vector and Authentication Tag values remaining separate from the Ciphertext value in the output representation.  Also deleted the header parameters "epu"(encryption PartyUInfo) and "epv" (encryption PartyVInfo), since they are no longer used.
### 

Will you update the gem to work properly with this change in the draft? If you know what changes should be made in `JSON::JWE` perhaps i'll be able to code them.

An example of the problem i have. Trying to decode with A128CBC+HS256 i have this error when calling `JSON::JWE#decrypt!` method:

`OpenSSL::Cipher::CipherError Exception: wrong final block length`

Thanks.

**Comment by kkarras** [comment]
@bensw I believe I'm running into the same thing with a MSFT JWE.

Been trying to decrypt but not having success.

Should I still try and use older version of this gem and decompress as mentioned above?

**Comment by balauru** [comment]
I was facing a similar problem, using version 0.5.6 of the gem, my code is:

```ruby
def inflate_jwe(jwe_string)
  zstream = Zlib::Inflate.new(-15)
  buf = zstream.inflate(jwe_string)
  zstream.finish
  zstream.close

  buf
end

def decrypt!(data)
  jwe = JSON::JWT.decode(data, default_private_key).to_s
  inflate_jwe(jwe)
end

output = UrlSafeBase64.decode64(decrypt!(data))
```

The part that I was missing was to decode64 the data after it was inflated.
