### ISSUE TITLE
ECDSA signatures are not generated correctly

### ISSUE THREAD

**Issue by jurriaan** [nov/json-jwt#21]
You cannot use the `private_key.dsa_sign_asn1` output directly as signature. The JWS signature consists of the concatenated R and S integers. [RFC7515 appendix A.3.1](http://tools.ietf.org/html/rfc7515#appendix-A.3.1)

See also https://github.com/progrium/ruby-jwt/pull/87 and https://github.com/progrium/ruby-jwt/issues/84

**Comment by nov** [comment]
I hope my fix works for you.
If you still has issues, please let me know.
