### ISSUE TITLE
kid is being considered required

### ISSUE THREAD

**Issue by guilhermednt** [nov/json-jwt#28]
I don't know much ruby, but as far as I could understand, [this code](https://github.com/nov/json-jwt/blob/master/lib/json/jws.rb#L116) is considering the `kid` as `REQUIRED` whereas the [RFC states](https://tools.ietf.org/html/rfc7515#section-4.1.4) that `Use of this Header Parameter is OPTIONAL.`

The JWT in question gets validated successfully at [jwt.io](http://jwt.io/).

I just want to let you know this is happening. I'll just use the `kid` anyways since it seems to be a good practice.

**Comment by nov** [comment]
The code you mentioned is used only when your singing/encryption key input is an instance of `JSON::JWK::Set` (jwks).
Only in that case, `kid` is required.
If your input is `JSON::JWK` or other ruby-native RSS/EC key object, `kid` is still OPTIONAL.

**Comment by guilhermednt** [comment]
Oh, ok. Thanks for clarifying @nov! :)

Btw, nice work with `openid_connect_sample_rp`! It's helping me a **lot**.

**Comment by nov** [comment]
cool ;)
