### ISSUE TITLE
Default `:kid` as thumbprint

### ISSUE THREAD

**Issue by futureperfect** [nov/json-jwt#33]
I had the idea last night that it might be useful for `json-jwt` to set up a default `:kid` for new JWK, then noticed you had pushed changes to add (c1c632d) and then revert (2ca766b) that change at almost exactly the same time that I had the idea. Out of curiosity, can you share what you're thinking?

**Comment by nov** [comment]
The code raised when `JSON::JWK.new` is called with no arguments.

**Comment by futureperfect** [comment]
Thanks for the insight and thank you for writing this library. I'm curious to see what you ultimately end up going with.

For now I'm manually setting `:kid` to thumbprint, but I could see the niceness of maybe:

1. having either a better default constructor (i.e. making it impossible to publish an invalid JWK)
2. creating a nice way to specify that the `:kid` should be the thumbprint, e.g.

    ```ruby
    jwk = JWK.new(pem).with_default_kid
    ```
Or something that accomplishes the same goal.

**Comment by nov** [comment]
This is what I'm planning now, but I'm feeling I need more beta period for this feature.
https://github.com/nov/json-jwt/pull/34
