### ISSUE TITLE
Activesupport requires ruby >= 2.2.2

### ISSUE THREAD

**Issue by funzoneq** [nov/json-jwt#35]
Ruby support for 2.1 is broken by activesupport 5.0.x.

Please pin to activesupport to 4.2.6 if ruby < 2.2

**Comment by jhass** [comment]
Or we just get rid of it, see #29

**Comment by nov** [comment]
can't bundler solve it?

**Comment by mattolson** [comment]
👍 I just ran into this as well. Seems like a good short term fix is to update the dependency to < 5
