### ISSUE TITLE
1.6.2 broke backwards compatibility, no longer sets algorithm when signing JWT

### ISSUE THREAD

**Issue by nhinds** [nov/json-jwt#39]
In 1.6.2, JSON::JWT.sign started calling `JWS.new self.dup` instead of `JSW.new self`.

This has caused `acme-client`, who depends on `json-jwt`, to start failing with errors "algorithm 'none' in JWS header not acceptable": unixcharles/acme-client#74

Editing `lib/json/jwt.rb` and removing `.dup` makes these errors go away. The errors are not present when running with `json-jwt` 1.5.2 or 1.6.1, so it seems like something has broken backwards compatibility in the patch version 1.6.2.

**Comment by nhinds** [comment]
It looks like calling `.dup` sets the copied `JSON::JWT` object's `alg` to `:none`:

```
2.3.1 :004 > jwt=JSON::JWT.new
 => {} 
2.3.1 :005 > jwt.alg
 => :none 
2.3.1 :006 > jwt.alg = :foo
 => :foo 
2.3.1 :007 > jwt.alg
 => :foo 
2.3.1 :008 > jwt.dup
 => {} 
2.3.1 :009 > jwt.dup.alg
 => :none 
2.3.1 :010 > jwt.alg
 => :foo 
```

It looks like calling `.dup` doesn't retain other fields like `.crit`, `.jwk`, etc. either, so I'm not sure that `.dup` actually keeps any of the `JSON::JWT` object's state

**Comment by nhinds** [comment]
Sorry! This is a dupe of #37, which still affects the latest rubygems.org version but has been fixed on master

**Comment by nhinds** [comment]
Looks like this problem still affects 1.6.3 which has the fix for #37

Specifically, the following code used to work, but no longer does:
```
require 'openssl'
require 'json/jwt'

private_key = OpenSSL::PKey::RSA.new(4096)
jwt = JSON::JWT.new({'some' => 'data'})
jwt.header[:jwk] = JSON::JWK.new(private_key.public_key)
jwt.signature = jwt.sign(private_key, :RS256).signature

fail "Wanted :RS256 but got #{jwt.alg.inspect}" unless jwt.alg == :RS256
```

The above works fine in 1.5.2, 1.6.0, and 1.6.1. It fails on 1.6.2 and 1.6.3 with:

    json-jwt-39.rb:9:in `<main>': Wanted :RS256 but got :none (RuntimeError)

The fix for #37 stopped calling `.dup`, but made some other change that prevents this from working. It looks like calling `jwt.sign` used to update `jwt` with the algorithm used (and possibly some other things), but this no longer happens, and the above pattern fails.

**Comment by nov** [comment]
jwt.sign() returns a new jws object.
original jwt isn't modified.
please read README

**Comment by nhinds** [comment]
Sure - but `jwt.sign` *did* modify the original object for all versions up until 1.6.2, and the behaviour was changed in a patch version, which is breaking the other library I use :(

**Comment by nhinds** [comment]
Worked around this change in unixcharles/acme-client#91
