### ISSUE TITLE
Any objection to me adding a :skip_verification example to your wiki docs?

### ISSUE THREAD

**Issue by theirishpenguin** [nov/json-jwt#41]
I propose adding this section. It appears I have permission to edit that wiki page but I just want to clear it with you @nov. My use case is when I get a key verification failure I'd still like decode token so I can see what went wrong...

### Decode without verifying (not recommended, use for debugging only)

```ruby
id_token = JSON::JWT.decode id_token_string, :skip_verification
puts id_token.to_json
```

**Comment by nov** [comment]
looks good.
thanks

**Comment by theirishpenguin** [comment]
Cool. Done at at https://github.com/nov/json-jwt/wiki

Thanks again for these libraries.
