### ISSUE TITLE
Can payload for signing with JWT be a string instead of a json

### ISSUE THREAD

**Issue by Phuong5664** [nov/json-jwt#49]
Hi,
I'm just wondering if there is a way to sign a message as a string?? Like:

payload = 'my string to sign'
signed_message = JSON::JWT.new(payload).sign(my_private_key, :RS256)

instead of:
payload = {
  foo: 'my string to sign'
}
Thanks in advance and appreciate your help!

**Comment by nov** [comment]
you can't.

**Comment by jphastings** [comment]
@Phuong5664 that wouldn't be a JSON web token (see [RFC 7519](https://tools.ietf.org/html/rfc7519) for the specification) — but you can sign an arbitrary string [using OpenSSL directly](https://gist.github.com/gevans/6004752#file-sign-verify-rb) if you want to!
