### ISSUE TITLE
Thread safety?

### ISSUE THREAD

**Issue by franklinyu** [nov/json-jwt#50]
For example, given a `$jwk` which is a `JSON::JWK::Set`, would there be race condition when multiple threads do `JSON::JWT.decode(token, $jwk)` simultaneously?

**Comment by nov** [comment]
why did you think so?

**Comment by franklinyu** [comment]
I don't "think so"; I was just wondering whether thread safety was in mind when developing this library, because (surprisingly?) not every library author would like to consider such cases. Some would even explicitly state in README like

> This library is *not* meant for threaded Ruby applications

, so race condition is not considered bug there. It is not obvious what is mutated in each method, and I would like to double check before I do optimization in production code.
