### ISSUE TITLE
Encrypt then Sign

### ISSUE THREAD

**Issue by tfluehmann** [nov/json-jwt#58]
Sign then encrypt enforces the server to decrypt the token before the validation of the sender can be verified. From my point of view this seems to be inefficient and not best practice.
Am I right, that the gem just supports the method sign then encrypt and not encrypt then sign?

**Comment by nov** [comment]
Right.
This gem doesn’t support JWS with plaintext payload, so you can’t sign against encrypted and compact-serialized JWE.
