### ISSUE TITLE
Relation with ruby-jwt gem

### ISSUE THREAD

**Issue by printercu** [nov/json-jwt#67]
Hi! Can you please clarify if there any difference between this gem and https://github.com/jwt/ruby-jwt ? Which one should I use in new project?

Thank you!

**Comment by FranklinYu** [comment]
1. They have a different API.
2. JWT (JSON Web Token) is (to some extend) JWS (JSON Web Signature) plus JWE (JSON Web Encryption). This gem fully supports JWT; that gem claims to support JWT but it actually only supports JWS. See jwt/ruby-jwt#80.
