### ISSUE TITLE
Token to string doesn't match the original compact token

### ISSUE THREAD

**Issue by MatteoJoliveau** [nov/json-jwt#71]
Good evening,
we are using this gem to decode and verify OpenID Connect tokens.
Since we are using it to authenticate different services with each other, after verification we sometimes need to send the token back to the auth service. That's how we discovered that doing `token.to_s` is not idempotent. In particular:
```ruby
@token = 'myjwttoken'

JSON::JWT.decode(@token, 'secret').to_s == @token # => false
```

Any idea why, and how can we fix this problem?

/cc @emaserafini

**Comment by nov** [comment]
I don't get what's your problem. Just use `@token` for string comparison purpose.
