### ISSUE TITLE
Push tag v1.10.0

### ISSUE THREAD

**Issue by MITSUBOSHI** [nov/json-jwt#72]
Hi, it seems json-jwt v1.10.0 is available.
https://rubygems.org/gems/json-jwt/versions/1.10.0
However, there is no tags for v1.10.0 on GitHub. Could you push it?

**Comment by matthutchinson** [comment]
+1 yep this is weird, it gives the impression that a gem release was published to RubyGems without any trace of it on GitHub.

**Comment by FranklinYu** [comment]
I compared version 1.10.0 and current master faa74c9da017a5e72b59d49e852c40ba41198b2f. There are only two differences:

1. The `VERSION` file is updated (of course).
2. The submodule `spec/helpers/jwt-nimbus` is removed.

For security’s sake this is fine, but I would pin the dependency at 1.10.0 and inspect future updates manually.

**Comment by nov** [comment]
sorry, but I can't find that.
