### ISSUE TITLE
Support for Unencoded Payload Option (RFC 7797)

### ISSUE THREAD

**Issue by idigber** [nov/json-jwt#77]
Is there support for JWS Unencoded Payload Option (RFC 7797) for signature calculation using this library? More details can be found here: https://tools.ietf.org/html/rfc7797

**Comment by nov** [comment]
use `JSON::JWT#as_json` instead of `JSON::JWT#to_s`

**Comment by DeanDeBlock** [comment]
`to_s` or` to_json` is for a JWT instance, but is there a possibility to verify a separate payload with an input like this (no encoded payload) for example: `YyEb2883..Jhdr334` ?

**Comment by nov** [comment]
Sorry, I don't get what you mean.

**Comment by nov** [comment]
Ah, I got it.
So, the correct answer is this gem doesn't support RFC 7797.
