### ISSUE TITLE
uninitialized constant JSON::JWT

### ISSUE THREAD

**Issue by GMolini** [nov/json-jwt#99]
Im trying to load this gem into a rails project but for some reason when I try to use it I get an `uninitialized constant JSON::JWT` error.

Ive just included 
`gem 'json-jwt'` in my Gemfile, like usual, then did bundle install. Ive never had this type of issue.
Do you have any idea why this might be happening?
Thanks

**Comment by nov** [comment]
sorry, no idea.

**Comment by ddiachkov** [comment]
Had the same problem. In my case, `oj_mimic_json` was replacing JSON const. Putting `json-jwt` **before** `oj` fixed the problem:

```
gem 'json-jwt'
gem 'oj'
gem 'oj_mimic_json'
```
